### ISSUE TITLE
Having a custom renderer for VideoView 

### ISSUE THREAD

**Issue by tombby11** [Rod-at-Rox/RoxXamarinVideo#3]
Hello , first of all I would like to say 1000 thanks for your great job. 
Second of all , I myself have an implementation for VLC on Xamarin.forms but just for android , in case you would like to have a look at it. 
Now, Lets say for some reasons I would like to use the vlclib or ExoPlayer instead of the default VideoView in Android , Is there a way to have a custom rendered for your videoView ? it would be nice to have access to such custom renderers

**Comment by Rod-at-Rox** [comment]
Hey tombby11, thank you. I am too busy until next week to look at this, but I definitely will check out your component. Basically, I personally had the requirement to target iOS and UWP, and implemented a basic Android version whilst I was there, meaning that I have never given much effort to the Android implementation, and I know it has a couple of issues. It is also possible for me to expose the renderers, I will check out what is best practice for this. Again, I won't have the time to even look at this until next week at the earliest, thanks again and I will keep you posted.

**Comment by Rod-at-Rox** [comment]
Sorry, but I have no intention of exposing the custom renderers for next version 2.1.0. I will may revisit this in the future. I also will not be replacing the android custom renderer for next version, I will determine which of the available Android video renderers best suits my needs and I will replace the Android custom renderer in a future version soon.

**Comment by tombby11** [comment]
So what are your intentions for the next releases ? :) i am just curious

**Comment by Rod-at-Rox** [comment]
At the moment I have fixed a couple of minor issues with UWP, the VideoView has been optimised for virtualization (use within ListView etc) which is undergoing testing for all platforms, I have introduced Duration and Position properties in UWP, will be implemented for iOS and Android, created FullScreen property for UWP, implementing FullScreen for iOS and Android probably won't happen this release, I have a fix for the Android landscape left-aligned instead of centered issue which I want to get in too, and I have implemented StreamImageSource for iOS and Android (already worked for UWP). I think that is it, the priorities are currently based on what I require.
